validate:
	terraform validate

apply:
	terraform apply -var-file=inputs.tfvars -auto-approve

plan:
	terraform plan -var-file=inputs.tfvars

destroy:
	terraform destroy -var-file=inputs.tfvars -auto-approve
